# Generated by Django 5.0.4 on 2024-12-28 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.BigAutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('cp_commune', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('commune', models.CharField(max_length=30)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acommune.region')),
            ],
        ),
    ]
