# Generated by Django 5.0.4 on 2025-10-23 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acommune', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['province']},
        ),
    ]
