# Generated by Django 5.0.4 on 2025-08-22 13:05

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Facturation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeRecette',
            fields=[
                ('id_type_recette', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id_recette', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('date_encaissement', models.DateField(db_default=django.db.models.functions.datetime.Now())),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Facturation.facture')),
                ('type_recette', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Recette.typerecette')),
            ],
            options={
                'ordering': ['-date_encaissement', '-created_at'],
                'indexes': [models.Index(fields=['date_encaissement'], name='Recette_rec_date_en_932936_idx'), models.Index(fields=['type_recette'], name='Recette_rec_type_re_a90384_idx'), models.Index(fields=['facture'], name='Recette_rec_facture_2907ab_idx')],
            },
        ),
    ]
