# Generated by Django 5.0.4 on 2025-10-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recette', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='id_recette',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typerecette',
            name='id_type_recette',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
