# Generated by Django 5.0.2 on 2024-03-06 18:53

import Compteurs.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compteur',
            fields=[
                ('num_compteur', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('marque_compteur', models.CharField(max_length=30)),
                ('modele_compteur', models.CharField(max_length=30)),
                ('DN_compteur', models.CharField(max_length=5)),
                ('origin_compteur', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReleveCompteur',
            fields=[
                ('id_releve', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_releve', models.DateField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('conso', models.IntegerField(blank=True, null=True)),
                ('image_compteur', models.ImageField(blank=True, upload_to=Compteurs.models.upload_to_compteur)),
                ('num_compteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relevecompteurs', to='Compteurs.compteur')),
            ],
        ),
    ]
