# Generated by Django 5.0.1 on 2024-03-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compteurs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteur',
            name='num_compteur',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
