# Generated by Django 5.0.4 on 2026-01-15 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compteurs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteurPrincipale',
            fields=[
                ('num_compteur_principale', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Numéro')),
                ('marque_compteur_principale', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marque')),
                ('modele_compteur_principale', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modèle')),
                ('DN_compteur_principale', models.CharField(blank=True, max_length=100, null=True, verbose_name='DN')),
                ('origin_compteur_principale', models.CharField(blank=True, max_length=100, null=True, verbose_name='Origine')),
            ],
            options={
                'verbose_name': 'Compteur Principal',
                'verbose_name_plural': 'Compteurs Principaux',
            },
        ),
        migrations.AddField(
            model_name='compteur',
            name='num_compteur_principale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compteurs', to='Compteurs.compteurprincipale'),
        ),
        migrations.CreateModel(
            name='ReleveCompteurPrincipale',
            fields=[
                ('id_releve', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_releve', models.DateField(blank=True, null=True, verbose_name='Date du relevé')),
                ('volume', models.IntegerField(blank=True, null=True, verbose_name='Volume (m³)')),
                ('conso', models.IntegerField(blank=True, null=True, verbose_name='Consommation (m³)')),
                ('image_compteur', models.ImageField(blank=True, upload_to='compteurs_principaux/', verbose_name='Photo')),
                ('num_compteur_principale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves', to='Compteurs.compteurprincipale', verbose_name='Compteur Principal')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relevé Compteur Principal',
                'verbose_name_plural': 'Relevés Compteurs Principaux',
                'ordering': ['-date_releve'],
            },
        ),
    ]
