# Generated by Django 5.0.4 on 2026-01-15 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compteurs', '0003_compteurprincipale_compteur_num_compteur_principale_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteConsommation',
            fields=[
                ('id_alerte', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_alerte', models.CharField(choices=[('PERTE', 'Perte détectée'), ('ECART_ELEVE', 'Écart élevé'), ('ECART_CRITIQUE', 'Écart critique')], default='PERTE', max_length=20)),
                ('message', models.TextField(verbose_name='Message')),
                ('ecart_m3', models.IntegerField(verbose_name='Écart (m³)')),
                ('pourcentage_ecart', models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Pourcentage d'écart")),
                ('conso_principal', models.IntegerField(verbose_name='Consommation Principal (m³)')),
                ('conso_sous_compteurs', models.IntegerField(verbose_name='Consommation Sous-Compteurs (m³)')),
                ('date_releve', models.DateField(verbose_name='Date du relevé concerné')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('statut', models.CharField(choices=[('NON_LU', 'Non lu'), ('LU', 'Lu'), ('TRAITE', 'Traité'), ('IGNORE', 'Ignoré')], default='NON_LU', max_length=10)),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('compteur_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='Compteurs.compteurprincipale', verbose_name='Compteur Principal')),
                ('utilisateur_traitement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
            ],
            options={
                'verbose_name': 'Alerte Consommation',
                'verbose_name_plural': 'Alertes Consommation',
                'ordering': ['-date_creation'],
            },
        ),
    ]
