# Generated by Django 5.0.4 on 2026-01-18 08:50
# Modified to generate unique UUIDs for existing records

import uuid
import django.utils.timezone
from django.db import migrations, models


def generate_unique_sync_ids_compteur(apps, schema_editor):
    """Génère des UUIDs uniques pour les compteurs existants"""
    Compteur = apps.get_model('Compteurs', 'Compteur')
    for compteur in Compteur.objects.all():
        compteur.sync_id = uuid.uuid4()
        compteur.save(update_fields=['sync_id'])


def generate_unique_sync_ids_releve(apps, schema_editor):
    """Génère des UUIDs uniques pour les relevés existants"""
    ReleveCompteur = apps.get_model('Compteurs', 'ReleveCompteur')
    for releve in ReleveCompteur.objects.all():
        releve.sync_id = uuid.uuid4()
        releve.save(update_fields=['sync_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('Compteurs', '0004_alerteconsommation'),
    ]

    operations = [
        # ===============================
        # Champs pour Compteur
        # ===============================
        migrations.AddField(
            model_name='compteur',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, 
                db_index=True, 
                default=django.utils.timezone.now, 
                verbose_name='Date de création'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compteur',
            name='deleted_at',
            field=models.DateTimeField(
                blank=True, 
                null=True, 
                verbose_name='Date de suppression'
            ),
        ),
        migrations.AddField(
            model_name='compteur',
            name='is_deleted',
            field=models.BooleanField(
                db_index=True, 
                default=False, 
                help_text='Marqueur de suppression logique (soft delete)', 
                verbose_name='Supprimé'
            ),
        ),
        migrations.AddField(
            model_name='compteur',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True, 
                db_index=True, 
                verbose_name='Date de modification'
            ),
        ),
        migrations.AddField(
            model_name='compteur',
            name='version',
            field=models.PositiveIntegerField(
                default=1, 
                help_text='Numéro de version pour la détection de conflits', 
                verbose_name='Version'
            ),
        ),
        # Ajouter sync_id sans contrainte unique d'abord
        migrations.AddField(
            model_name='compteur',
            name='sync_id',
            field=models.UUIDField(
                db_index=True, 
                default=uuid.uuid4, 
                editable=False, 
                help_text='Identifiant unique pour la synchronisation', 
                null=True,  # Temporairement nullable
                verbose_name='ID de synchronisation'
            ),
        ),
        # Générer des UUIDs uniques pour les enregistrements existants
        migrations.RunPython(
            generate_unique_sync_ids_compteur,
            reverse_code=migrations.RunPython.noop
        ),
        # Modifier le champ pour ajouter la contrainte unique
        migrations.AlterField(
            model_name='compteur',
            name='sync_id',
            field=models.UUIDField(
                db_index=True, 
                default=uuid.uuid4, 
                editable=False, 
                help_text='Identifiant unique pour la synchronisation', 
                unique=True,
                verbose_name='ID de synchronisation'
            ),
        ),

        # ===============================
        # Champs pour ReleveCompteur
        # ===============================
        migrations.AddField(
            model_name='relevecompteur',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, 
                db_index=True, 
                default=django.utils.timezone.now, 
                verbose_name='Date de création'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relevecompteur',
            name='deleted_at',
            field=models.DateTimeField(
                blank=True, 
                null=True, 
                verbose_name='Date de suppression'
            ),
        ),
        migrations.AddField(
            model_name='relevecompteur',
            name='is_deleted',
            field=models.BooleanField(
                db_index=True, 
                default=False, 
                help_text='Marqueur de suppression logique (soft delete)', 
                verbose_name='Supprimé'
            ),
        ),
        migrations.AddField(
            model_name='relevecompteur',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True, 
                db_index=True, 
                verbose_name='Date de modification'
            ),
        ),
        migrations.AddField(
            model_name='relevecompteur',
            name='version',
            field=models.PositiveIntegerField(
                default=1, 
                help_text='Numéro de version pour la détection de conflits', 
                verbose_name='Version'
            ),
        ),
        # Ajouter sync_id sans contrainte unique d'abord
        migrations.AddField(
            model_name='relevecompteur',
            name='sync_id',
            field=models.UUIDField(
                db_index=True, 
                default=uuid.uuid4, 
                editable=False, 
                help_text='Identifiant unique pour la synchronisation', 
                null=True,  # Temporairement nullable
                verbose_name='ID de synchronisation'
            ),
        ),
        # Générer des UUIDs uniques pour les enregistrements existants
        migrations.RunPython(
            generate_unique_sync_ids_releve,
            reverse_code=migrations.RunPython.noop
        ),
        # Modifier le champ pour ajouter la contrainte unique
        migrations.AlterField(
            model_name='relevecompteur',
            name='sync_id',
            field=models.UUIDField(
                db_index=True, 
                default=uuid.uuid4, 
                editable=False, 
                help_text='Identifiant unique pour la synchronisation', 
                unique=True,
                verbose_name='ID de synchronisation'
            ),
        ),
    ]
