# Generated by Django 5.0.4 on 2026-01-19 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compteurs', '0005_add_sync_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='relevecompteur',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='relevecompteur',
            name='motif_rejet',
            field=models.TextField(blank=True, null=True, verbose_name='Motif du rejet'),
        ),
        migrations.AddField(
            model_name='relevecompteur',
            name='statut_validation',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('CONFIRME', 'Confirmé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=15, verbose_name='Statut de validation'),
        ),
        migrations.AddField(
            model_name='relevecompteur',
            name='valideur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releves_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AlterField(
            model_name='relevecompteur',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='releves_effectues', to=settings.AUTH_USER_MODEL, verbose_name='Agent'),
        ),
    ]
