# Generated by Django 5.0.4 on 2026-03-15 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compteurs', '0006_relevecompteur_date_validation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreAlerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seuil_alerte', models.FloatField(default=5.0, help_text='Pourcentage à partir duquel une alerte est créée', verbose_name="Seuil d'alerte (%)")),
                ('seuil_critique', models.FloatField(default=10.0, help_text="Pourcentage à partir duquel l'alerte est critique", verbose_name='Seuil critique (%)')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('utilisateur_modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': "Paramètre d'Alerte",
                'verbose_name_plural': "Paramètres d'Alerte",
            },
        ),
    ]
