# Generated by Django 5.0.4 on 2024-12-28 01:15

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id_historique', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_historique', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('type_historique', models.CharField(max_length=100)),
            ],
        ),
    ]
