# Generated by Django 5.0.2 on 2024-03-06 18:53

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id_historique', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_historique', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('type_historique', models.CharField(max_length=100)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
