version: '4.28'

services:
  django:
    container_name: rel_compteur
    build:
      context: ./
    command:
      - py manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Rel_Compteur:/usr/src/app
    ports:
      - "8001:8000"
    environment:
      - DEBUG:1
      - SECRET_KEY=2&e6eh3@0idjnee^vf$ft(ff1vzs@uhfg)3n@zna@f#7pmz14v
      - ALLOWED_HOSTS=localhost,127.0.0.1