networks:
  webapp_preprod:
  traefik_preprod:
    external: true

services:
  db:
    image: postgres:16
    container_name: eatc-db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always
    networks:
      - webapp_preprod

  web:
    build: .
    container_name: eatc-web
    command: gunicorn Rel_Compteur.wsgi:application --bind 0.0.0.0:8000 --workers 3
    env_file: .env
    volumes:
      - .:/app
    labels:
      - traefik.enable=true
      - traefik.http.routers.eatc.rule=Host(`app.eatc.me`)
      - traefik.http.routers.eatc.entrypoints=websecure
      - traefik.http.routers.eatc.tls.certresolver=myresolver
      - traefik.http.services.eatc.loadbalancer.server.port=8000
      - traefik.docker.network=traefik_preprod
    depends_on:
      - db
    restart: always
    networks:
      - webapp_preprod
      - traefik_preprod

volumes:
  postgres_data:
