# Generated by Django 5.0.4 on 2025-03-19 18:03

import Tenants.models
import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Acommune', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=100)),
                ('schema_name', models.CharField(max_length=100, verbose_name='Base de donnée')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='Tenants.entreprise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_utilisateur', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_utilisateur', models.CharField(max_length=30, verbose_name='Nom')),
                ('prenom_utilisateur', models.CharField(max_length=50, verbose_name='Prénom')),
                ('num_utilisateur', models.CharField(max_length=10, unique=True, verbose_name='Contact')),
                ('photo_utilisateur', models.ImageField(blank=True, null=True, upload_to=Tenants.models.upload_to_utilisateur)),
                ('cree_le', models.DateField(auto_now_add=True)),
                ('statut', models.BooleanField(db_default=True, verbose_name='Active')),
                ('last_token', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Pseudo')),
                ('cp_commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acommune.commune', verbose_name='Commune')),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Tenants.entreprise')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Tenants.role')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Initial',
            fields=[
                ('id_initial', models.BigAutoField(primary_key=True, serialize=False)),
                ('utilisateur_createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initials', to=settings.AUTH_USER_MODEL)),
                ('utilisateur_cree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
