# Generated by Django 5.0.4 on 2025-01-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='num_utilisateur',
            field=models.CharField(max_length=10),
        ),
    ]
