# Generated by Django 5.0.4 on 2025-06-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='logo_entreprise',
            field=models.ImageField(blank=True, upload_to='logo_entreprise', verbose_name='Logo'),
        ),
    ]
