# Generated by Django 5.0.4 on 2025-01-20 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='createur',
        ),
    ]
