# Generated by Django 5.0.4 on 2025-03-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(blank=True, default=0, max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
