# Generated by Django 5.0.4 on 2024-12-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Pseudo'),
        ),
    ]
