# Generated by Django 5.0.4 on 2025-06-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0002_entreprise_logo_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='signature_entreprise',
            field=models.ImageField(blank=True, upload_to='signature/entreprise', verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='logo_entreprise',
            field=models.ImageField(blank=True, upload_to='logo/entreprise', verbose_name='Logo'),
        ),
    ]
