# Generated by Django 5.0.4 on 2025-07-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0003_entreprise_signature_entreprise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='nif',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NIF'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='stat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='STAT'),
        ),
    ]
