# Generated by Django 5.0.4 on 2025-07-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0005_entreprise_numero_mvola'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='nom_mvola',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Nom Mvola'),
        ),
    ]
