# Generated by Django 5.0.4 on 2026-03-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0006_entreprise_nom_mvola'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='representant_legal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Représentant légal'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='siege_social',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Siège social'),
        ),
    ]
