# Generated by Django 5.0.4 on 2026-03-28 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0007_entreprise_representant_legal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='last_token',
        ),
    ]
