# Generated by Django 5.0.4 on 2025-07-31 19:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id_category', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID Catégorie')),
                ('nom_categorie', models.CharField(max_length=255, unique=True, verbose_name='Nom de la catégorie')),
            ],
            options={
                'ordering': ['nom_categorie'],
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id_transaction', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_transaction', models.DateField(default=django.utils.timezone.now, verbose_name='Date de transaction')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant')),
                ('numero_recu', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de reçu')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='Depense.categories', verbose_name='Catégorie')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'ordering': ['-date_transaction'],
                'indexes': [models.Index(fields=['date_transaction'], name='Depense_tra_date_tr_b81518_idx'), models.Index(fields=['categorie'], name='Depense_tra_categor_9cff37_idx')],
            },
        ),
    ]
