# Generated by Django 5.0.4 on 2026-02-14 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acommune', '0002_alter_province_options'),
        ('Depense', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='cp_commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acommune.commune', verbose_name='Commune'),
        ),
        migrations.AddIndex(
            model_name='transactions',
            index=models.Index(fields=['cp_commune'], name='Depense_tra_cp_comm_a1d375_idx'),
        ),
    ]
