# Generated by Django 5.0.4 on 2025-03-19 18:03

import Main_Courante.models
import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Acommune', '0001_initial'),
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoMC',
            fields=[
                ('id_photos', models.BigAutoField(primary_key=True, serialize=False)),
                ('photo_anomalie', models.ImageField(blank=True, upload_to=Main_Courante.models.upload_to_mc)),
            ],
        ),
        migrations.CreateModel(
            name='StatutMC',
            fields=[
                ('id_statut', models.BigAutoField(primary_key=True, serialize=False)),
                ('en_cours', models.BooleanField(default=False)),
                ('realise', models.BooleanField(default=False)),
                ('non_traite', models.BooleanField(default=True)),
                ('date_status', models.DateField(blank=True, db_default=django.db.models.functions.datetime.Now(), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuivieMC',
            fields=[
                ('id_suivie', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_suivie', models.DateTimeField()),
                ('commentaire_suivie', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MainCourante',
            fields=[
                ('id_mc', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_mc', models.DateField(default=django.utils.timezone.now)),
                ('type_anomalie', models.CharField(max_length=50)),
                ('longitude_mc', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude_mc', models.CharField(blank=True, max_length=50, null=True)),
                ('description_mc', models.CharField(max_length=255)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Clients.client')),
                ('cp_commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acommune.commune')),
            ],
        ),
    ]
