# Generated by Django 5.0.4 on 2024-04-30 06:44

import Main_Courante.models
import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCourante',
            fields=[
                ('id_mc', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_mc', models.DateField(default=django.utils.timezone.now)),
                ('type_anomalie', models.CharField(max_length=30)),
                ('longitude_mc', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude_mc', models.CharField(blank=True, max_length=50, null=True)),
                ('description_mc', models.CharField(max_length=50)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Clients.client')),
                ('cp_commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clients.commune')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoMC',
            fields=[
                ('id_photos', models.BigAutoField(primary_key=True, serialize=False)),
                ('photo_anomalie', models.ImageField(blank=True, upload_to=Main_Courante.models.upload_to_mc)),
                ('main_courante', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='photomcs', to='Main_Courante.maincourante')),
            ],
        ),
        migrations.CreateModel(
            name='StatutMC',
            fields=[
                ('id_statut', models.BigAutoField(primary_key=True, serialize=False)),
                ('en_cours', models.BooleanField(default=False)),
                ('realise', models.BooleanField(default=False)),
                ('non_traite', models.BooleanField(default=True)),
                ('date_status', models.DateField(blank=True, db_default=django.db.models.functions.datetime.Now(), null=True)),
                ('main_courante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuts', to='Main_Courante.maincourante')),
            ],
        ),
        migrations.CreateModel(
            name='SuivieMC',
            fields=[
                ('id_suivie', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_suivie', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('commentaire_suivie', models.CharField(max_length=200)),
                ('main_courante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suiviemcs', to='Main_Courante.maincourante')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
