# Generated by Django 5.0.4 on 2024-05-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Courante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincourante',
            name='description_mc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='maincourante',
            name='type_anomalie',
            field=models.CharField(max_length=50),
        ),
    ]
