# Generated by Django 5.0.4 on 2026-01-18 11:45

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Courante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincourante',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maincourante',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AddField(
            model_name='maincourante',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Marqueur de suppression logique (soft delete)', verbose_name='Supprimé'),
        ),
        migrations.AddField(
            model_name='maincourante',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identifiant unique pour la synchronisation', unique=True, verbose_name='ID de synchronisation'),
        ),
        migrations.AddField(
            model_name='maincourante',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date de modification'),
        ),
        migrations.AddField(
            model_name='maincourante',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Numéro de version pour la détection de conflits', verbose_name='Version'),
        ),
    ]
