# Generated by Django 5.0.4 on 2025-03-19 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main_Courante', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maincourante',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photomc',
            name='main_courante',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='photomcs', to='Main_Courante.maincourante'),
        ),
        migrations.AddField(
            model_name='statutmc',
            name='main_courante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuts', to='Main_Courante.maincourante'),
        ),
        migrations.AddField(
            model_name='suiviemc',
            name='main_courante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suiviemcs', to='Main_Courante.maincourante'),
        ),
        migrations.AddField(
            model_name='suiviemc',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
