# Generated by Django 5.0.4 on 2026-01-18 11:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Courante', '0002_maincourante_created_at_maincourante_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincourante',
            name='sync_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
