# Generated by Django 5.0.4 on 2024-06-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Courante', '0002_alter_maincourante_description_mc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statutmc',
            name='date_status',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suiviemc',
            name='date_suivie',
            field=models.DateTimeField(),
        ),
    ]
