# Generated by Django 5.0.4 on 2024-06-14 06:34

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Courante', '0003_alter_statutmc_date_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statutmc',
            name='date_status',
            field=models.DateField(blank=True, db_default=django.db.models.functions.datetime.Now(), null=True),
        ),
    ]
