# Generated by Django 5.0.2 on 2024-03-06 18:53

import Login.models
import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0002_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_utilisateur', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_utilisateur', models.CharField(max_length=30)),
                ('prenom_utilisateur', models.CharField(max_length=50)),
                ('num_utilisateur', models.TextField(max_length=10)),
                ('password', models.TextField(max_length=200)),
                ('photo_utilisateur', models.ImageField(blank=True, null=True, upload_to=Login.models.upload_to_utilisateur)),
                ('cree_le', models.DateField(db_default=django.db.models.functions.datetime.Now())),
                ('statut', models.BooleanField(db_default=True)),
                ('last_token', models.CharField(blank=True, max_length=255, null=True)),
                ('cp_commune', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Clients.commune')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Login.role')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Initial',
            fields=[
                ('id_initial', models.BigAutoField(primary_key=True, serialize=False)),
                ('utilisateur_createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initials', to=settings.AUTH_USER_MODEL)),
                ('utilisateur_cree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
