# Generated by Django 5.0.4 on 2026-03-26 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileVersion',
            fields=[
                ('id_version', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Version')),
                ('version', models.CharField(max_length=20, unique=True, verbose_name='Version')),
                ('filename', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('file', models.FileField(upload_to='login/apk/', verbose_name='Fichier APK')),
                ('taille', models.CharField(max_length=20, verbose_name='Taille')),
                ('changelog', models.TextField(blank=True, verbose_name='Notes de version')),
                ('est_actuelle', models.BooleanField(default=False, verbose_name='Version actuelle')),
                ('maj_forcee', models.BooleanField(default=False, verbose_name='Mise à jour forcée')),
                ('telecharge_le', models.DateTimeField(auto_now_add=True, verbose_name='Date de téléchargement')),
                ('nombre_telechargements', models.IntegerField(default=0, verbose_name='Nombre de téléchargements')),
                ('statut', models.CharField(choices=[('active', 'Active'), ('archivee', 'Archivée'), ('supprimee', 'Supprimée')], default='active', max_length=20, verbose_name='Statut')),
                ('telecharge_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Téléchargé par')),
            ],
            options={
                'verbose_name': 'Version Mobile',
                'verbose_name_plural': 'Versions Mobile',
                'ordering': ['-telecharge_le'],
            },
        ),
    ]
