# Generated by Django 5.0.1 on 2024-01-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='last_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
