# Generated by Django 5.0.4 on 2026-03-26 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial_mobile_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadToken',
            fields=[
                ('id_token', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Token')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('expires_at', models.DateTimeField(verbose_name="Date d'expiration")),
                ('used', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'utilisation")),
                ('download_count', models.IntegerField(default=0, verbose_name='Nombre de téléchargements')),
                ('max_downloads', models.IntegerField(default=5, verbose_name='Max téléchargements')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('mobile_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tokens', to='Login.mobileversion', verbose_name='Version mobile')),
            ],
            options={
                'verbose_name': 'Token de Téléchargement',
                'verbose_name_plural': 'Tokens de Téléchargement',
                'ordering': ['-created_at'],
            },
        ),
    ]
