# Generated by Django 5.0.2 on 2024-02-24 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0003_initial'),
        ('Login', '0002_utilisateur_last_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='cp_commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Clients.commune'),
        ),
    ]
