# Generated by Django 5.0.2 on 2024-04-30 02:26

import Clients.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('cp_commune', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('commune', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PieceClient',
            fields=[
                ('id_piece', models.BigAutoField(primary_key=True, serialize=False)),
                ('pieces_client', models.FileField(blank=True, upload_to=Clients.models.upload_to_client)),
                ('designation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.BigAutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TypeClient',
            fields=[
                ('id_type_client', models.BigAutoField(primary_key=True, serialize=False)),
                ('designation_client', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_client', models.CharField(max_length=50)),
                ('prenom_client', models.CharField(blank=True, max_length=30, null=True)),
                ('tel1_client', models.CharField(max_length=10)),
                ('tel2_client', models.CharField(max_length=10, null=True)),
                ('email_client', models.TextField(max_length=60, null=True)),
                ('adresse_client', models.TextField(max_length=100)),
                ('pays_client', models.CharField(max_length=30)),
                ('compte_actif', models.BooleanField(default=False)),
                ('cp_commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='Clients.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('num_contrat', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('adresse_contrat', models.CharField(max_length=100)),
                ('pays_contrat', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='Clients.client')),
                ('cp_commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.commune')),
            ],
        ),
    ]
