# Generated by Django 5.0.2 on 2024-04-23 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0001_initial'),
        ('Compteurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='num_compteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='Compteurs.compteur'),
        ),
    ]
