# Generated by Django 5.0.4 on 2025-04-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nb_personne_menage',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='profession_client',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
