# Generated by Django 5.0.4 on 2025-04-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_client_nb_personne_menage_client_profession_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adresse_client',
            field=models.TextField(max_length=128),
        ),
        migrations.AlterField(
            model_name='client',
            name='profession_client',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='tel1_client',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='tel2_client',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
