# Generated by Django 5.0.2 on 2024-04-23 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='piececlient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piececlients', to='Clients.client'),
        ),
        migrations.AddField(
            model_name='commune',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.region'),
        ),
        migrations.AddField(
            model_name='client',
            name='type_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='Clients.typeclient'),
        ),
    ]
