# Generated by Django 5.0.4 on 2025-04-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0003_alter_client_adresse_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email_client',
            field=models.TextField(default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='nb_personne_menage',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='pays_client',
            field=models.CharField(default='Madagascar', max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom_client',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='profession_client',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='tel1_client',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='tel2_client',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
