# Generated by Django 5.0.4 on 2025-06-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0004_alter_client_email_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='prenom_client',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
