# Generated by Django 5.0.4 on 2025-06-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0005_alter_client_prenom_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='num_client',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
