# Generated by Django 5.0.4 on 2025-11-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0006_client_num_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeclient',
            options={'ordering': ['designation_client']},
        ),
    ]
