# Generated by Django 5.0.4 on 2026-01-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0007_alter_typeclient_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeclient',
            name='designation_client',
            field=models.CharField(max_length=100),
        ),
    ]
