# Generated by Django 5.0.4 on 2025-10-29 18:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Acommune', '0002_alter_province_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitEau',
            fields=[
                ('id_debit', models.BigAutoField(primary_key=True, serialize=False)),
                ('debit', models.IntegerField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_modification', models.DateField(auto_now=True)),
                ('cp_commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acommune.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Marnage',
            fields=[
                ('id_marnage', models.BigAutoField(primary_key=True, serialize=False)),
                ('marnage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date_creation', models.CharField(blank=True, max_length=16, null=True)),
                ('date_modification', models.DateField(auto_now=True)),
                ('cp_commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acommune.commune')),
            ],
        ),
    ]
