# Generated by Django 5.0.4 on 2025-10-23 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Acommune', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitEau',
            fields=[
                ('id_debit', models.AutoField(primary_key=True, serialize=False)),
                ('debit', models.IntegerField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('cp_commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acommune.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Marnage',
            fields=[
                ('id_marnage', models.AutoField(primary_key=True, serialize=False)),
                ('marnage', models.IntegerField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('cp_commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acommune.commune')),
            ],
        ),
    ]
