# Generated by Django 5.0.4 on 2025-10-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debiteau',
            name='id_debit',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='marnage',
            name='id_marnage',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
