# Generated by Django 5.0.4 on 2025-10-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debiteau',
            name='debit',
            field=models.FloatField(),
        ),
    ]
