# Generated by Django 5.0.4 on 2025-10-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrique', '0002_alter_debiteau_id_debit_alter_marnage_id_marnage'),
    ]

    operations = [
        migrations.AddField(
            model_name='debiteau',
            name='date_modification',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='marnage',
            name='date_modification',
            field=models.DateField(auto_now=True),
        ),
    ]
