# Generated by Django 5.0.4 on 2025-10-28 05:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrique', '0003_debiteau_date_modification_marnage_date_modification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marnage',
            name='marnage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
