# Generated by Django 5.0.4 on 2025-10-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rubrique', '0004_alter_marnage_marnage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marnage',
            name='date_creation',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
