# Generated by Django 5.0.4 on 2025-03-27 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBranchement',
            fields=[
                ('id_config_branchement', models.BigAutoField(primary_key=True, serialize=False)),
                ('tva_applique', models.BooleanField(default=False)),
                ('type_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.typeclient')),
            ],
        ),
    ]
