# Generated by Django 5.0.4 on 2024-06-14 06:39

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Compteurs', '0001_initial'),
        ('Facturation', '0001_initial'),
        ('Main_Courante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syncronisation',
            fields=[
                ('id_syncro', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_syncro', models.DateField(blank=True, db_default=django.db.models.functions.datetime.Now(), null=True)),
                ('message_serveur', models.CharField(blank=True, max_length=30, null=True)),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Facturation.facture')),
                ('main_courante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main_Courante.maincourante')),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Facturation.paiement')),
                ('relevercompteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Compteurs.relevecompteur')),
            ],
        ),
    ]
