# Generated by Django 5.0.4 on 2025-11-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ranoo_Config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configbranchement',
            options={'ordering': ['type_client__designation_client']},
        ),
    ]
