# Generated by Django 5.0.4 on 2024-06-26 05:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id_facture', models.BigAutoField(primary_key=True, serialize=False)),
                ('num_facture', models.CharField(max_length=50)),
                ('date_facture_precedant', models.DateField(blank=True, null=True)),
                ('date_facture', models.DateField()),
                ('montant_total_ttc', models.FloatField(blank=True, null=True)),
                ('avoir_avant', models.FloatField(blank=True, null=True)),
                ('avoir_utilise', models.FloatField(blank=True, null=True)),
                ('avoir_nouveau', models.FloatField(blank=True, null=True)),
                ('restant_precedant', models.FloatField(blank=True, null=True)),
                ('restant_nouvel', models.FloatField(blank=True, null=True)),
                ('statut', models.BooleanField(default=False)),
                ('taxes_appliquees', models.JSONField(blank=True, null=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('tva_appliquer', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MontantHT',
            fields=[
                ('id_montant_ht', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_conso_ht', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MontantTTC',
            fields=[
                ('id_montant_ttc', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_conso_ttc', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id_paiement', models.BigAutoField(primary_key=True, serialize=False)),
                ('montant_payer', models.FloatField(blank=True, null=True)),
                ('date_paiement', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Restant',
            fields=[
                ('id_restant', models.BigAutoField(primary_key=True, serialize=False)),
                ('restant', models.FloatField()),
                ('date_restant', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id_tarif', models.BigAutoField(primary_key=True, serialize=False)),
                ('prix_m3_bs', models.FloatField(blank=True, null=True)),
                ('prix_m3_bp', models.FloatField(blank=True, null=True)),
                ('prix_m3_k', models.FloatField(blank=True, null=True)),
                ('tva', models.FloatField()),
                ('conso_tva_app', models.FloatField(blank=True, null=True)),
                ('nb_jour_echeance_fct', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Taxe',
            fields=[
                ('id_taxe', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_taxe', models.CharField(default='Taxe', max_length=100)),
                ('taux_taxe', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Avoir',
            fields=[
                ('id_avoir', models.BigAutoField(primary_key=True, serialize=False)),
                ('montant_avoir', models.FloatField()),
                ('date_avoir', models.DateField(default=django.utils.timezone.now)),
                ('num_contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avoirs', to='Clients.contrat')),
            ],
        ),
    ]
