# Generated by Django 5.0.4 on 2024-05-30 16:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0003_initial'),
        ('Compteurs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avoir',
            fields=[
                ('id_avoir', models.BigAutoField(primary_key=True, serialize=False)),
                ('montant_avoir', models.FloatField()),
                ('date_avoir', models.DateField(default=django.utils.timezone.now)),
                ('num_contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avoirs', to='Clients.contrat')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id_facture', models.BigAutoField(primary_key=True, serialize=False)),
                ('num_facture', models.CharField(max_length=50)),
                ('date_facture', models.DateField()),
                ('montant_total_ttc', models.FloatField(blank=True, null=True)),
                ('avoir_avant', models.FloatField(blank=True, null=True)),
                ('avoir_utilise', models.FloatField(blank=True, null=True)),
                ('restant_precedant', models.FloatField(blank=True, null=True)),
                ('restant_nouvel', models.FloatField(blank=True, null=True)),
                ('statut', models.BooleanField(default=False)),
                ('num_contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.contrat')),
                ('relevecompteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='Compteurs.relevecompteur')),
            ],
        ),
        migrations.CreateModel(
            name='MontantHT',
            fields=[
                ('id_montant_ht', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_conso_ht', models.FloatField()),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facturation.facture')),
            ],
        ),
        migrations.CreateModel(
            name='MontantTTC',
            fields=[
                ('id_montant_ttc', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_conso_ttc', models.FloatField()),
                ('montant_ht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montantttc', to='Facturation.montantht')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id_paiement', models.BigAutoField(primary_key=True, serialize=False)),
                ('montant_payer', models.FloatField(blank=True, null=True)),
                ('date_paiement', models.DateField(default=django.utils.timezone.now)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='Facturation.facture')),
            ],
        ),
        migrations.CreateModel(
            name='Restant',
            fields=[
                ('id_restant', models.BigAutoField(primary_key=True, serialize=False)),
                ('restant', models.FloatField()),
                ('date_restant', models.DateField(default=django.utils.timezone.now)),
                ('num_contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restants', to='Clients.contrat')),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id_tarif', models.BigAutoField(primary_key=True, serialize=False)),
                ('prix_m3_bs', models.FloatField(blank=True, null=True)),
                ('prix_m3_bp', models.FloatField(blank=True, null=True)),
                ('prix_m3_k', models.FloatField(blank=True, null=True)),
                ('tva', models.FloatField()),
                ('conso_tva_app', models.FloatField(blank=True, null=True)),
                ('nb_jour_echeance_fct', models.IntegerField()),
                ('cp_commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='Clients.commune')),
            ],
        ),
        migrations.AddField(
            model_name='montantht',
            name='tarif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facturation.tarif'),
        ),
        migrations.CreateModel(
            name='Taxe',
            fields=[
                ('id_taxe', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_taxe', models.CharField(default='Taxe', max_length=100)),
                ('taux_taxe', models.FloatField()),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='Facturation.tarif')),
            ],
        ),
    ]
