# Generated by Django 5.0.4 on 2025-03-19 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Acommune', '0001_initial'),
        ('Clients', '0002_initial'),
        ('Compteurs', '0002_initial'),
        ('Facturation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avoir',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facture',
            name='num_contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.contrat'),
        ),
        migrations.AddField(
            model_name='facture',
            name='relevecompteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='Compteurs.relevecompteur'),
        ),
        migrations.AddField(
            model_name='montantht',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facturation.facture'),
        ),
        migrations.AddField(
            model_name='montantttc',
            name='montant_ht',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montantttc', to='Facturation.montantht'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='Facturation.facture'),
        ),
        migrations.AddField(
            model_name='restant',
            name='num_contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restants', to='Clients.contrat'),
        ),
        migrations.AddField(
            model_name='restant',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarif',
            name='cp_commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='Acommune.commune'),
        ),
        migrations.AddField(
            model_name='montantht',
            name='tarif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facturation.tarif'),
        ),
        migrations.AddField(
            model_name='taxe',
            name='tarif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='Facturation.tarif'),
        ),
    ]
