# Generated by Django 5.0.2 on 2024-03-01 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facturation', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='montantht',
            name='total_redevance_bs_ht',
        ),
        migrations.RemoveField(
            model_name='montantht',
            name='total_redevance_fr_ht',
        ),
        migrations.RemoveField(
            model_name='montantht',
            name='total_taxe_co_ht',
        ),
    ]
