# Generated by Django 5.0.4 on 2024-06-22 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturation', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueTaxe',
            fields=[
                ('id_hist_taxe', models.BigAutoField(primary_key=True, serialize=False)),
                ('taxes_appliquees', models.JSONField(blank=True, null=True)),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='Facturation.facture')),
                ('tarif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='Facturation.tarif')),
            ],
        ),
    ]
