# Generated by Django 5.0.4 on 2025-01-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='prix_location_compteur',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
