# Generated by Django 5.0.1 on 2024-03-11 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturation', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='montantht',
            name='total_redevance_bs_ht',
        ),
        migrations.RemoveField(
            model_name='montantht',
            name='total_redevance_fr_ht',
        ),
        migrations.RemoveField(
            model_name='montantht',
            name='total_taxe_co_ht',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='redevance_bs',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='redevance_fr',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='taxe_co',
        ),
        migrations.CreateModel(
            name='Taxe',
            fields=[
                ('id_taxe', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_taxe', models.CharField(default='Taxe', max_length=100)),
                ('taux_taxe', models.FloatField(max_length=100)),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='Facturation.tarif')),
            ],
        ),
    ]
