# Generated by Django 5.0.2 on 2024-03-01 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturation', '0003_remove_montantht_total_redevance_bs_ht_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxe',
            name='tarif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='Facturation.tarif'),
        ),
    ]
