# Generated by Django 5.0.4 on 2025-01-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturation', '0003_tarif_prix_location_compteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='conso_tva_app',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='prix_location_compteur',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='tva',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
