# Generated by Django 5.0.4 on 2024-06-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturation', '0003_historiquetaxe'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='taxes_appliquees',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='HistoriqueTaxe',
        ),
    ]
