# Generated by Django 5.0.4 on 2025-01-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturation', '0004_alter_tarif_conso_tva_app_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxe',
            name='taux_taxe',
            field=models.FloatField(default=0),
        ),
    ]
