# Generated by Django 5.0.4 on 2024-06-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturation', '0004_facture_taxes_appliquees_delete_historiquetaxe'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date_echeance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
