# Generated by Django 5.0.4 on 2024-06-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturation', '0005_facture_date_echeance'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='tva_appliquer',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
