# Generated by Django 5.0.4 on 2024-06-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturation', '0006_facture_tva_appliquer'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date_facture_precedant',
            field=models.DateField(blank=True, null=True),
        ),
    ]
